In [13]:
import numpy as np
import pandas as pd

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier

In [15]:
df = pd.read_csv('sample_data/titanic_data.csv')

In [16]:
df.head(),

(   PassengerId  Survived  Pclass  \
 0            1         0       3
 1            2         1       1
 2            3         1       3
 3            4         1       1
 4            5         0       3

                                                 Name     Sex   Age  SibSp  \
 0                            Braund, Mr. Owen Harris    male  22.0      1
 1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
 2                             Heikkinen, Miss. Laina  female  26.0      0
 3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
 4                           Allen, Mr. William Henry    male  35.0      0

    Parch            Ticket     Fare Cabin Embarked
 0      0         A/5 21171   7.2500   NaN        S
 1      0          PC 17599  71.2833   C85        C
 2      0  STON/O2. 3101282   7.9250   NaN        S
 3      0            113803  53.1000  C123        S
 4      0            373450   8.0500   NaN        S  ,)

# Let's Plan

In [17]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [18]:
# Step 1 -> train/test/split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Survived']),
                                                 df['Survived'],
                                                 test_size=0.2,
                                                random_state=42)

In [19]:
X_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [20]:
y_train.sample(5)

308    0
122    0
528    0
813    0
522    0
Name: Survived, dtype: int64

In [21]:
# imputation transformer
step1_imputation = ColumnTransformer([
    ('impute_age',SimpleImputer(),[2]),
    ('impute_embarked',SimpleImputer(strategy='most_frequent'),[6])
],remainder='passthrough')

In [22]:
# one hot encoding
step2_encoding = ColumnTransformer([
    ('ohe_sex_embarked',OneHotEncoder(sparse_output=False,handle_unknown='ignore'),[1,6])
],remainder='passthrough')

In [23]:

# Scaling
step3_scaling = ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,10))
])

In [24]:
# Feature selection
step4_featureSelection = SelectKBest(score_func=chi2,k=8)

In [25]:
# train the model
step5_loadModel = DecisionTreeClassifier()

# Create Pipeline

In [44]:
pipe = Pipeline([
    ('imputation',step1_imputation),
    ('enconding',step2_encoding),
    ('scaling',step3_scaling),
    ('feature_selection',step4_featureSelection),
    ('model_training',step5_loadModel)
])

# Pipeline Vs make_pipeline

Pipeline requires naming of steps, make_pipeline does not.

(Same applies to ColumnTransformer vs make_column_transformer)

In [27]:
# Alternate Syntax
pipe = make_pipeline(step1_imputation,step2_encoding,step3_scaling,step4_featureSelection,step5_loadModel)

In [28]:
# train
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('columntransformer-3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('selectkbest',
                 SelectKBest(k=8,
                             score_func=<function chi2 at 0x7b7f80e4f6a0>)),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

# Explore the Pipeline

In [45]:
# Code here
pipe.named_steps

{'imputation': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_age', SimpleImputer(), [2]),
                                 ('impute_embarked',
                                  SimpleImputer(strategy='most_frequent'),
                                  [6])]),
 'enconding': ColumnTransformer(remainder='passthrough',
                   transformers=[('ohe_sex_embarked',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [1, 6])]),
 'scaling': ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 10, None))]),
 'feature_selection': SelectKBest(k=8, score_func=<function chi2 at 0x7b7f80e4f6a0>),
 'model_training': DecisionTreeClassifier()}

In [46]:
# Display Pipeline

from sklearn import set_config
set_config(display='diagram')

In [47]:
# Predict
y_pred = pipe.predict(X_test)

In [48]:
y_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0])

In [49]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6256983240223464

# Cross Validation using Pipeline

In [50]:
# cross validation using cross_val_score
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X_train, y_train, cv=5, scoring='accuracy').mean()

np.float64(0.6391214419383433)

# GridSearch using Pipeline

In [53]:
# gridsearchcv
params = {
    'model_training__max_depth':[1,2,3,4,5,None]
}

In [54]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(pipe, params, cv=5, scoring='accuracy')
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('imputation',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('impute_age',
                                                                         SimpleImputer(),
                                                                         [2]),
                                                                        ('impute_embarked',
                                                                         SimpleImputer(strategy='most_frequent'),
                                                                         [6])])),
                                       ('enconding',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ohe_sex_embarked',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         [1,
                                                                          6])])),
                                       ('scaling',
                                        ColumnTransformer(transformers=[('scale',
                                                                         MinMaxScaler(),
                                                                         slice(0, 10, None))])),
                                       ('feature_selection',
                                        SelectKBest(k=8,
                                                    score_func=<function chi2 at 0x7b7f80e4f6a0>)),
                                       ('model_training',
                                        DecisionTreeClassifier())]),
             param_grid={'model_training__max_depth': [1, 2, 3, 4, 5, None]},
             scoring='accuracy')

In [55]:
grid.best_score_

np.float64(0.6391214419383433)

In [56]:
grid.best_params_

{'model_training__max_depth': 2}

# Exporting the Pipeline

In [57]:
# export
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))

In [43]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S